### ISSUE TITLE
Question: will this work with the Proto Muse board?

### ISSUE THREAD

**Issue by tomlut** [balloob/squeezelite-esp32-install#1]
It looks perfect for replacing my Chromesast Audio.

**Comment by balloob** [comment]
Yes it works as per: https://forum.raspiaudio.com/t/multirooms-with-squeezelite-with-esp32-muse-proto/291

I will update the installer to support the proto board too. I have one arriving today.

**Comment by tomlut** [comment]
Thanks!

**Comment by balloob** [comment]
Added PR to add it to the installer https://github.com/balloob/squeezelite-esp32-install/pull/2
